name: Envio Relatorio Semanal

on:
  schedule:
    # Segunda-feira 08:00 Brasil (UTC-3) = 11:00 UTC
    - cron: "0 11 * * 1"
  workflow_dispatch:

jobs:
  chamar-function:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar Azure Function para envio do email
        run: |
          curl -i -s -S -X GET "https://func-relatorio-dabrfqcmf7hmajh6.azurewebsites.net/api/email/teste"
